language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

script:
  - ./gradlew clean build check

cache:
  directories:
    - $HOME/.gradle
