# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BAdapter
email: biaoliu_2007@163.com
description: A graceful RecyclerView Adapter.

url: "https://biaowu.github.io/BAdapter"

github_username:  BiaoWu

# Build settings
markdown: kramdown
